apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: koncepts
  name: koncepts
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: koncepts
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: koncepts
    spec:
      containers:
      - env:
        - name: DISCOVERY_HOSTNAME
          value: koncepts-headless
        image: quay.io/srowley/koncepts:latest
        imagePullPolicy: Always
        name: koncepts
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/etc/content
          name: config-volume
      volumes:
      - configMap:
          name: config-files
        name: config-volume